# Generated by Django 4.0.5 on 2023-01-02 13:20

import Places.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('thumbnail_image', models.ImageField(default='thumbnail_default.jpg', upload_to=Places.models.content_file_name)),
            ],
        ),
    ]
